<?php
/**
 * Implementa hook_menu().
 */

function sw_menu() {

  $items['sw/rest'] = array(
    'title' => 'Saludar',
    'page callback' => 'sw_rest',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Callback que implementa la páina: sw/rest
 */
function sw_rest() {

  $aux=  include_once('node.php'); 
  if (!$aux ) {
	 $arr = 
	    array(
	        "fecha" =>" ",
	        "titulo" => ' ',
	        "lenguaje" => ' ',
	        "contenido" => ' ',
	        "imagen" => ' ',
	        "comentarios" =>' '    
	  );
	  return json_encode($arr);
  }

  $obj = new nodo();
  //variables post vacias
  if(empty($_POST['index']) && empty($_POST['idNode']) && empty($_POST['comentario']) ){
	$obj->jsonEmpty();
  }

  //información básica de todos los nodos
  if (!empty($_POST["index"]) && empty($_POST["idNode"]) && empty($_POST["comentario"])) {
	#require_once('node.php'); 
      $obj->getAll();
  }

  //Para obtener el nodo, o publicacioón
  if(!empty($_POST["idNode"]) && empty($_POST["comentario"]) && empty($_POST["index"])){
    	#require_once('node.php'); 
	$obj->getNode($_POST["idNode"]);
  }
  
  //Agregar comentarios
  if(!empty($_POST["comentario"]) && !empty($_POST["idNode"]) && empty($_POST["index"]) ) {
	#require_once('comments.php'); 
	$obj->addComment($_POST["comentario"],$_POST["idNode"]);
  }


}


?>
