<?php
/**
 * Implementa hook_menu().
 */

function sw_menu() {

  $items['sw/rest'] = array(
    'title' => 'Saludar',
    'page callback' => 'sw_rest',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Callback que implementa la páina: sw/rest
 */
function sw_rest() {

  $aux=  include_once('node.php'); 
  if (!$aux ) {
	 $arr = 
	    array(
	        "fecha" =>" ",
	        "titulo" => ' ',
	        "lenguaje" => ' ',
	        "contenido" => ' ',
	        "imagen" => ' ',
	        "comentarios" =>' '    
	  );
	  return json_encode($arr);
  }

  $idNode=(int)$_POST["idNode"];
  $comentario=$_POST["comentario"];
  $index=$_POST["index"];

  $obj = new nodo();
  //variables post vacias
  if(empty($index) && empty($idNode) && empty($comentario) ){ 
    $obj->jsonEmpty();
  } 

  //información básica de todos los nodos
  if (!empty($index) && empty($idNode) && empty($comentario) ) {
        $obj->getAll();
  }

  //Para obtener el nodo, o publicacioón
  if(!empty($idNode && empty($comentario && empty($index) ){
    if ($idNode< 10 && $idNode > 0)
	   $obj->getNode($idNode);
    else
      $obj->jsonEmpty();   
  }
  
  //Agregar comentarios
  if(!empty($comentario) && !empty($idNode) && empty($index) ) {
	  $obj->addComment($comentario,$idNode);
  }


}


?>
