<?php
/**
 * Implementa hook_menu().
 */
function sw_menu() {
  $items['sw/rest'] = array(
    'title' => 'Saludar',
    'page callback' => 'sw_rest',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Callback que implementa la páina: sw/rest
 */
function sw_rest() {

 	

  //Para obtener el nodo, o publicacioón
  if(!empty($_POST["idNode"]) && empty($_POST["comentario"])){
    require_once('node.php'); 
    getNode($_POST["idNode"]);
  }
  
  if(!empty($_POST["comentario"]) && !empty($_POST["idNode"]) ) {
    require_once('comments.php'); 
    addComment($_POST["comentario"],$_POST["idNode"]);
  }

}


?>